const KISAN_MARG_DATA = {
  profiles: [
    {
      id: "KM-2401",
      name: "Rajesh Patil",
      role: "Farmer",
      village: "Rampur",
      district: "Amravati",
      phone: "+91 98765 43210",
      language: "Marathi",
      land: "5 Acres",
      crops: "Wheat, Cotton, Tomato",
      status: "Active"
    },
    {
      id: "KM-2402",
      name: "Sunita Kale",
      role: "Farmer",
      village: "Pimpalgaon",
      district: "Nashik",
      phone: "+91 99887 66554",
      language: "Hindi",
      land: "3 Acres",
      crops: "Onion, Soybean",
      status: "Pending Review"
    },
    {
      id: "KM-2403",
      name: "Meera Deshmukh",
      role: "Admin",
      village: "Nagpur City",
      district: "Nagpur",
      phone: "+91 91234 56780",
      language: "English",
      land: "Platform",
      crops: "Operations",
      status: "Active"
    }
  ],

  market: {
    Wheat: { location: "Nashik", direct: 32, mandi: 30, trader: 27, trend: [25, 27, 27, 28, 30, 31, 32] },
    Soybean: { location: "Nagpur", direct: 52, mandi: 48, trader: 44, trend: [42, 44, 45, 46, 47, 49, 52] },
    Onion: { location: "Lasalgaon", direct: 18, mandi: 15, trader: 12, trend: [10, 11, 12, 13, 14, 15, 18] },
    Cotton: { location: "Amravati", direct: 74, mandi: 69, trader: 63, trend: [58, 60, 61, 64, 66, 70, 74] }
  },

  weather: [
    { title: "Today", note: "28°C · Light wind · Good for sowing", crop: "Delay cotton spray till evening humidity drops." },
    { title: "Tomorrow", note: "26°C · Rain expected after 6 PM", crop: "Avoid fertilizer spraying before rainfall." },
    { title: "Climate Note", note: "Low rainfall trend across nearby districts", crop: "Bajra and pulses are safer than soybean without irrigation." }
  ],

  schemes: [
    { name: "PM-Kisan", desc: "Income support in direct installments for eligible farmers." },
    { name: "PMFBY", desc: "Insurance support for crop loss and climate damage." },
    { name: "Soil Health Card", desc: "Soil testing and nutrient-based farming recommendations." }
  ],
  
  aiReplies: {
    disease: "Check whether the spots are spreading, yellow-bordered, or linked to excess moisture. Remove badly affected leaves, avoid overhead watering, and use crop-specific treatment based on severity. You can also upload an image for better guidance.",
    market: "Direct buyer prices are usually better than middleman offers when quality is verified. Compare mandi, direct, and trader rates before selling. I can help you decide whether to sell now or wait.",
    weather: "Weather changes spray timing, disease risk, and crop suitability. If rainfall stays low, pulses or bajra may be safer than soybean without irrigation backup.",
    schemes: "I can explain PM-Kisan, PMFBY, soil card support, or irrigation subsidy. Tell me whether you want eligibility, documents, or application steps.",
    app: "I can help you move through the app too. Ask me things like open crop care, show prices, or explain dashboard features."
  }
};

const KISAN_MARG_I18N = {
  en: {
    brandSub: "Smart Farming Companion",
    quickAccess: "Quick Access",
    moreFeatures: "Features",
    homeDashboardTitle: "Dashboard",
    homeDashboardDesc: "Daily farm overview with alerts, insights, and next steps",
    homeMarketTitle: "Market Prices",
    homeMarketDesc: "Live mandi and direct buyer rates in one place",
    homeCareTitle: "Crop Care",
    homeCareDesc: "Disease guidance, prevention, treatment, and image support",
    homeAiTitle: "AI Assistant",
    homeAiDesc: "Chat in Hindi, Marathi, or English for instant farming help",
    homeWeatherTitle: "Weather Forecast",
    homeWeatherDesc: "Forecasts and crop suggestions for changing conditions",
    homeSchemesTitle: "Government Schemes",
    homeSchemesDesc: "PM-Kisan, insurance, subsidy, and soil support",
    homeCommunityTitle: "Community Forum",
    homeCommunityDesc: "Learn from other farmers and share questions",
    homeAuthTitle: "Login / Signup",
    homeAuthDesc: "Farmer and admin access with mobile-friendly forms",
    navHome: "Home",
    navMarket: "Market",
    navAi: "AI",
    navProfile: "Profile",
    homeGreeting: "Namaste, Kisan Ji",
    homeTagline: "Your Smart\nFarming Companion",
    homeSub: "Real-time market prices · Weather guidance · Crop care · AI help",
    weatherStrip: "Amravati · 28°C · Live farming updates available",
    loginHeader: "Login",
    signupHeader: "Signup",
    aiPlaceholder: "Type your message here...",
    loginTitle: "Login to Kisan Marg",
    loginSub: "Enter as a farmer or admin. This is designed like a real mobile app screen that can later be wrapped for Android.",
    loginEmail: "Email or Phone",
    loginPassword: "Password",
    loginRole: "Login As",
    loginBtn: "Login",
    signupBtn: "Signup",
    signupTitle: "Create Farmer Profile",
    signupSub: "Register once and start using the dashboard, AI support, market updates, and crop care in a mobile-first flow.",
    signupName: "Full Name",
    signupPhone: "Phone",
    signupVillage: "Village",
    signupDistrict: "District",
    signupLanguage: "Preferred Language",
    signupLand: "Land Holding",
    signupCrops: "Main Crops",
    createAccount: "Create Account",
    back: "Back",
    dashboardHeader: "Dashboard",
    dashboardWelcome: "Welcome back,",
    todayFirst: "Today First",
    statWeather: "Weather",
    statWeatherHelp: "Rain likely after 6 PM",
    statBestRate: "Best Wheat Rate",
    statBestRateHelp: "Higher than trader offer",
    support: "Support",
    dashMarketTitle: "Market",
    dashMarketDesc: "Check best selling rate today",
    dashCareTitle: "Crop Care",
    dashCareDesc: "Disease, prevention, cure",
    dashAiTitle: "AI Bot",
    dashAiDesc: "Natural language assistance",
    dashAdminTitle: "Admin",
    dashAdminDesc: "Profiles and storage",
    dashWeatherTitle: "Weather & Climate Suggestions",
    dashWeatherDesc: "Get crop suggestions based on changing conditions",
    dashProfileTitle: "Profile",
    dashProfileDesc: "Farmer identity, crops, and preferences",
    marketHeader: "Market Prices",
    marketSub: "Live mandi rates from Indian agricultural markets",
    selectCrop: "Select Crop",
    marketTableMarket: "Market",
    marketTableLocation: "Location",
    marketTableRate: "Rate",
    marketMinPrice: "Min",
    marketModalPrice: "Modal",
    marketMaxPrice: "Max",
    marketDirectBuyer: "Direct Buyer",
    marketMandi: "APMC Mandi",
    marketTrader: "Middleman Offer",
    bestPriceToday: "Best Price Today",
    marketTrend: "Price trend",
    marketCompareTitle: "Top market comparison",
    marketLiveBadge: "Live",
    marketLoading: "Loading live market prices...",
    marketNoData: "No live mandi prices found for this selection.",
    marketErrorLoad: "Could not load live market prices right now.",
    marketFallbackNote: "Showing sample rates until live data is available.",
    cropCareHeader: "Crop Care",
    cropDoctorTitle: "AI Crop Doctor",
    cropDoctorDesc: "Describe symptoms in natural language or use image input for disease help, prevention, and cure guidance.",
    imagePlaceholder: "Image upload placeholder for leaf, fruit, stem, and pest-damage diagnosis",
    openAiDiagnosis: "Open AI Diagnosis",
    askCommunity: "Ask Community",
    detectTitle: "Symptoms",
    detectDesc: "Leaf curl, yellow spots, fungal growth, wilting, pest holes, nutrient deficiency",
    preventTitle: "Prevention",
    preventDesc: "Spacing, water control, crop hygiene, resistant seeds, and better spraying timing",
    treatTitle: "Treatment",
    treatDesc: "Safe cure suggestions, organic options, chemical support, and expert escalation",
    detectBadge: "Detect",
    preventBadge: "Prevent",
    treatBadge: "Treat",
    aiHeader: "AI Assistant",
    aiTitle: "KisanBot",
    aiDesc: "App surfing help, crop health tips, crop diseases, prevention, cure, climate updates, and crop suggestions.",
    aiPromptGreeting: "Hi",
    aiPromptCrop: "Crop advice",
    aiPromptPest: "Pest control",
    aiPromptMarket: "Market rates",
    aiPromptDisease: "Leaf disease",
    aiPromptClimate: "Climate crops",
    aiPromptApp: "App help",
    aiWelcome: "Namaste! Ask me anything about crops, weather, diseases, market prices, or how to use the app.",
    imageInputPlaceholder: "Image input placeholder for crop and leaf analysis",
    voiceInput: "Voice Input",
    voiceRecording: "Listening...",
    voiceTranscribing: "Processing...",
    voiceCropPrompt: "Speak your crop issue and I will move it to AI Diagnosis.",
    voiceReady: "Voice note ready for AI Diagnosis",
    voiceError: "Voice input could not be completed right now.",
    voiceUnsupported: "Voice input works best in Chrome on this device.",
    send: "Send",
    weatherHeader: "Weather & Climate",
    weatherSearchPlaceholder: "Search city (e.g., Amravati, Pune, Nashik)",
    weatherSearchBtn: "Search",
    weatherClearBtn: "Clear",
    weatherQuickLabel: "Quick Picks",
    weatherRecentsLabel: "Recent",
    weatherCurrentTitle: "Now",
    weatherMetaTitle: "At a glance",
    weatherForecastTitle: "7-Day Forecast",
    weatherLocalTime: "Local time",
    weatherFeelsLike: "Feels like",
    weatherWind: "Wind",
    weatherPrecip: "Precip",
    weatherClouds: "Clouds",
    weatherDayNight: "Day/Night",
    weatherTimezone: "Timezone",
    weatherLatitude: "Latitude",
    weatherLongitude: "Longitude",
    weatherElevation: "Elevation",
    weatherDay: "Day",
    weatherNight: "Night",
    weatherLoading: "Loading live weather...",
    weatherLoadingSearch: "Searching places...",
    weatherErrorShort: "Please enter at least 2 characters.",
    weatherErrorNoMatch: "No matching cities found.",
    weatherErrorSearch: "Search failed. Please try again.",
    weatherErrorLoad: "Could not load weather right now.",
    weatherResultSub: "Live forecast and current conditions",
    schemesHeader: "Government Schemes",
    communityHeader: "Community Forum",
    profileHeader: "Profile",
    profileDesc: "Farmer account, crops, and mobile app preferences",
    adminTitle: "Admin Storage",
    adminDesc: "Open profile management records",
    adminHeader: "Admin Storage",
    adminManageTitle: "Manage Profiles",
    adminManageDesc: "Farmer and admin records stored in local demo storage for the app flow",
    adminSearch: "Search Profiles",
    weatherBadge: "Climate",
    schemeBadge: "Scheme",
    forumBadge: "Forum",
    activeStatus: "Active",
    pendingStatus: "Pending Review",
    farmerId: "Farmer ID",
    villageDistrict: "Village and District",
    phoneLabel: "Phone",
    preferredLanguage: "Preferred Language",
    landHolding: "Land Holding",
    currentCrops: "Current Crops",
    weatherItems: [
      { title: "Today", note: "28°C · Light wind · Good for sowing", crop: "Delay cotton spray till evening humidity drops." },
      { title: "Tomorrow", note: "26°C · Rain expected after 6 PM", crop: "Avoid fertilizer spraying before rainfall." },
      { title: "Climate Note", note: "Low rainfall trend across nearby districts", crop: "Bajra and pulses are safer than soybean without irrigation." }
    ],
    schemeItems: [
      { name: "PM-Kisan", desc: "Income support in direct installments for eligible farmers." },
      { name: "PMFBY", desc: "Insurance support for crop loss and climate damage." },
      { name: "Soil Health Card", desc: "Soil testing and nutrient-based farming recommendations." }
    ],
    communityItems: [
      { title: "Best onion variety for this season?", meta: "Raju, Nashik · 12 replies" },
      { title: "How to stop tomato leaf blight early?", meta: "Savita, Pune · 8 replies" },
      { title: "Which mandi gave best wheat price today?", meta: "Ganesh, Amravati · 5 replies" }
    ],
    aiReplies: {
      disease: "Check whether the spots are spreading, yellow-bordered, or linked to excess moisture. Remove badly affected leaves, avoid overhead watering, and use crop-specific treatment based on severity. You can also upload an image for better guidance.",
      market: "Direct buyer prices are usually better than middleman offers when quality is verified. Compare mandi, direct, and trader rates before selling. I can help you decide whether to sell now or wait.",
      weather: "Weather changes spray timing, disease risk, and crop suitability. If rainfall stays low, pulses or bajra may be safer than soybean without irrigation backup.",
      schemes: "I can explain PM-Kisan, PMFBY, soil card support, or irrigation subsidy. Tell me whether you want eligibility, documents, or application steps.",
      app: "I can help you move through the app too. Ask me things like open crop care, show prices, or explain dashboard features."
    }
  },
  hi: {
    brandSub: "स्मार्ट खेती साथी",
    quickAccess: "त्वरित पहुँच",
    moreFeatures: "सुविधाएँ",
    homeDashboardTitle: "डैशबोर्ड",
    homeDashboardDesc: "अलर्ट, जानकारी और अगले कदमों के साथ दैनिक अवलोकन",
    homeMarketTitle: "बाजार भाव",
    homeMarketDesc: "लाइव मंडी और सीधे खरीदार की दरें एक ही जगह देखें",
    homeCareTitle: "फसल देखभाल",
    homeCareDesc: "रोग पहचान, रोकथाम, इलाज और इमेज सहायता",
    homeAiTitle: "AI सहायक",
    homeAiDesc: "हिंदी, मराठी या अंग्रेजी में तुरंत खेती सलाह पाएं",
    homeWeatherTitle: "मौसम पूर्वानुमान",
    homeWeatherDesc: "बदलती परिस्थितियों के लिए मौसम अपडेट और फसल सुझाव",
    homeSchemesTitle: "सरकारी योजनाएँ",
    homeSchemesDesc: "PM-Kisan, बीमा, सब्सिडी और मिट्टी सहायता",
    homeCommunityTitle: "कम्युनिटी फोरम",
    homeCommunityDesc: "दूसरे किसानों से सीखें और प्रश्न साझा करें",
    homeAuthTitle: "लॉगिन / साइनअप",
    homeAuthDesc: "मोबाइल-अनुकूल फ़ॉर्म के साथ किसान और एडमिन प्रवेश",
    navHome: "होम",
    navMarket: "बाजार",
    navAi: "AI",
    navProfile: "प्रोफाइल",
    homeGreeting: "नमस्ते, किसान जी",
    homeTagline: "आपका स्मार्ट\nखेती साथी",
    homeSub: "रियल-टाइम बाजार भाव · मौसम मार्गदर्शन · फसल देखभाल · AI सहायता",
    weatherStrip: "अमरावती · 28°C · लाइव खेती अपडेट उपलब्ध",
    loginHeader: "लॉगिन",
    signupHeader: "साइनअप",
    aiPlaceholder: "अपना संदेश यहाँ लिखें...",
    loginTitle: "किसान मार्ग में लॉगिन करें",
    loginSub: "किसान या एडमिन के रूप में प्रवेश करें। यह असली मोबाइल ऐप स्क्रीन की तरह बनाया गया है जिसे बाद में एंड्रॉयड में रैप किया जा सकता है।",
    loginEmail: "ईमेल या फोन",
    loginPassword: "पासवर्ड",
    loginRole: "इस रूप में लॉगिन करें",
    loginBtn: "लॉगिन",
    signupBtn: "साइनअप",
    signupTitle: "किसान प्रोफ़ाइल बनाएं",
    signupSub: "एक बार पंजीकरण करें और मोबाइल-फर्स्ट फ्लो में डैशबोर्ड, AI सहायता, बाजार अपडेट और फसल देखभाल का उपयोग करें।",
    signupName: "पूरा नाम",
    signupPhone: "फोन",
    signupVillage: "गाँव",
    signupDistrict: "जिला",
    signupLanguage: "पसंदीदा भाषा",
    signupLand: "भूमि होल्डिंग",
    signupCrops: "मुख्य फसलें",
    createAccount: "खाता बनाएं",
    back: "वापस",
    dashboardHeader: "डैशबोर्ड",
    dashboardWelcome: "फिर से स्वागत है,",
    todayFirst: "आज सबसे पहले",
    statWeather: "मौसम",
    statWeatherHelp: "शाम 6 बजे के बाद बारिश संभव",
    statBestRate: "आज गेहूं का सर्वोत्तम भाव",
    statBestRateHelp: "व्यापारी ऑफर से अधिक",
    support: "सहायता",
    dashMarketTitle: "बाजार",
    dashMarketDesc: "आज का सबसे अच्छा बिक्री भाव देखें",
    dashCareTitle: "फसल देखभाल",
    dashCareDesc: "रोग, रोकथाम, इलाज",
    dashAiTitle: "AI बॉट",
    dashAiDesc: "सामान्य भाषा में सहायता",
    dashAdminTitle: "एडमिन",
    dashAdminDesc: "प्रोफाइल और स्टोरेज",
    dashWeatherTitle: "मौसम और जलवायु सुझाव",
    dashWeatherDesc: "बदलती परिस्थितियों के अनुसार फसल सुझाव पाएं",
    dashProfileTitle: "प्रोफाइल",
    dashProfileDesc: "किसान पहचान, फसलें और पसंद",
    marketHeader: "बाजार भाव",
    marketSub: "भारतीय कृषि बाजारों से लाइव मंडी दरें",
    selectCrop: "फसल चुनें",
    marketTableMarket: "बाजार",
    marketTableLocation: "स्थान",
    marketTableRate: "दर",
    marketMinPrice: "न्यूनतम",
    marketModalPrice: "मोडल",
    marketMaxPrice: "अधिकतम",
    marketDirectBuyer: "सीधा खरीदार",
    marketMandi: "APMC मंडी",
    marketTrader: "बिचौलिया ऑफर",
    bestPriceToday: "आज का सर्वोत्तम भाव",
    marketTrend: "भाव रुझान",
    marketCompareTitle: "शीर्ष बाजार तुलना",
    marketLiveBadge: "लाइव",
    marketLoading: "लाइव बाजार भाव लोड हो रहे हैं...",
    marketNoData: "इस चयन के लिए कोई लाइव मंडी भाव नहीं मिला।",
    marketErrorLoad: "अभी लाइव बाजार भाव लोड नहीं हो सके।",
    marketFallbackNote: "लाइव डेटा उपलब्ध होने तक नमूना दरें दिखाई जा रही हैं।",
    cropCareHeader: "फसल देखभाल",
    cropDoctorTitle: "AI फसल डॉक्टर",
    cropDoctorDesc: "लक्षण सामान्य भाषा में बताएं या रोग, रोकथाम और इलाज सहायता के लिए इमेज इनपुट का उपयोग करें।",
    imagePlaceholder: "पत्ती, फल, तना और कीट-क्षति पहचान के लिए इमेज अपलोड प्लेसहोल्डर",
    openAiDiagnosis: "AI निदान खोलें",
    askCommunity: "कम्युनिटी से पूछें",
    detectTitle: "लक्षण",
    detectDesc: "पत्ती मुड़ना, पीले धब्बे, फफूंदी, मुरझाना, कीट छेद, पोषक कमी",
    preventTitle: "रोकथाम",
    preventDesc: "दूरी, जल नियंत्रण, खेत स्वच्छता, बेहतर बीज, सही स्प्रे समय",
    treatTitle: "उपचार",
    treatDesc: "सुरक्षित इलाज सुझाव, जैविक विकल्प, रासायनिक सहायता और विशेषज्ञ मदद",
    detectBadge: "पहचान",
    preventBadge: "रोकें",
    treatBadge: "इलाज",
    aiHeader: "AI सहायक",
    aiTitle: "किसानबॉट",
    aiDesc: "ऐप उपयोग सहायता, फसल स्वास्थ्य सुझाव, फसल रोग, रोकथाम, इलाज, जलवायु अपडेट और फसल सुझाव।",
    aiPromptGreeting: "नमस्ते",
    aiPromptCrop: "फसल सलाह",
    aiPromptPest: "कीट नियंत्रण",
    aiPromptMarket: "बाजार भाव",
    aiPromptDisease: "पत्ती रोग",
    aiPromptClimate: "जलवायु फसलें",
    aiPromptApp: "ऐप मदद",
    aiWelcome: "नमस्ते! मुझसे फसल, मौसम, रोग, बाजार भाव या ऐप उपयोग के बारे में कुछ भी पूछें।",
    imageInputPlaceholder: "फसल और पत्ती विश्लेषण के लिए इमेज इनपुट प्लेसहोल्डर",
    voiceInput: "आवाज़ इनपुट",
    voiceRecording: "सुन रहा हूँ...",
    voiceTranscribing: "प्रोसेस हो रहा है...",
    voiceCropPrompt: "अपनी फसल की समस्या बोलिए, मैं उसे AI निदान में भेज दूँगा।",
    voiceReady: "वॉइस नोट AI निदान के लिए तैयार है",
    voiceError: "अभी वॉइस इनपुट पूरा नहीं हो सका।",
    voiceUnsupported: "इस डिवाइस पर वॉइस इनपुट Chrome में बेहतर काम करता है।",
    send: "भेजें",
    weatherHeader: "मौसम और जलवायु",
    weatherSearchPlaceholder: "शहर खोजें (जैसे अमरावती, पुणे, नाशिक)",
    weatherSearchBtn: "खोजें",
    weatherClearBtn: "साफ करें",
    weatherQuickLabel: "त्वरित विकल्प",
    weatherRecentsLabel: "हाल के",
    weatherCurrentTitle: "अभी",
    weatherMetaTitle: "एक नज़र में",
    weatherForecastTitle: "7-दिन का पूर्वानुमान",
    weatherLocalTime: "स्थानीय समय",
    weatherFeelsLike: "महसूस",
    weatherWind: "हवा",
    weatherPrecip: "वर्षा",
    weatherClouds: "बादल",
    weatherDayNight: "दिन/रात",
    weatherTimezone: "टाइमज़ोन",
    weatherLatitude: "अक्षांश",
    weatherLongitude: "देशांतर",
    weatherElevation: "ऊंचाई",
    weatherDay: "दिन",
    weatherNight: "रात",
    weatherLoading: "लाइव मौसम लोड हो रहा है...",
    weatherLoadingSearch: "स्थान खोजे जा रहे हैं...",
    weatherErrorShort: "कृपया कम से कम 2 अक्षर लिखें।",
    weatherErrorNoMatch: "कोई मिलान करने वाला शहर नहीं मिला।",
    weatherErrorSearch: "खोज विफल रही। कृपया पुनः प्रयास करें।",
    weatherErrorLoad: "अभी मौसम लोड नहीं हो सका।",
    weatherResultSub: "लाइव पूर्वानुमान और वर्तमान स्थिति",
    schemesHeader: "सरकारी योजनाएँ",
    communityHeader: "कम्युनिटी फोरम",
    profileHeader: "प्रोफाइल",
    profileDesc: "किसान खाता, फसलें और मोबाइल ऐप प्राथमिकताएँ",
    adminTitle: "एडमिन स्टोरेज",
    adminDesc: "प्रोफाइल प्रबंधन रिकॉर्ड खोलें",
    adminHeader: "एडमिन स्टोरेज",
    adminManageTitle: "प्रोफाइल प्रबंधन",
    adminManageDesc: "ऐप फ्लो के लिए स्थानीय डेमो स्टोरेज में किसान और एडमिन रिकॉर्ड",
    adminSearch: "प्रोफाइल खोजें",
    weatherBadge: "जलवायु",
    schemeBadge: "योजना",
    forumBadge: "फोरम",
    activeStatus: "सक्रिय",
    pendingStatus: "समीक्षा लंबित",
    farmerId: "किसान आईडी",
    villageDistrict: "गाँव और जिला",
    phoneLabel: "फोन",
    preferredLanguage: "पसंदीदा भाषा",
    landHolding: "भूमि होल्डिंग",
    currentCrops: "वर्तमान फसलें",
    weatherItems: [
      { title: "आज", note: "28°C · हल्की हवा · बुवाई के लिए अच्छा", crop: "शाम तक नमी कम होने पर ही कपास स्प्रे करें।" },
      { title: "कल", note: "26°C · शाम 6 बजे के बाद बारिश", crop: "बारिश से पहले उर्वरक छिड़काव न करें।" },
      { title: "जलवायु नोट", note: "पास के जिलों में कम वर्षा का रुझान", crop: "बिना सिंचाई के सोयाबीन की बजाय बाजरा और दालें बेहतर हैं।" }
    ],
    schemeItems: [
      { name: "PM-Kisan", desc: "पात्र किसानों के लिए सीधे किस्तों में आय सहायता।" },
      { name: "PMFBY", desc: "फसल हानि और जलवायु नुकसान के लिए बीमा सहायता।" },
      { name: "सोइल हेल्थ कार्ड", desc: "मिट्टी परीक्षण और पोषक तत्व आधारित खेती सुझाव।" }
    ],
    communityItems: [
      { title: "इस मौसम के लिए सबसे अच्छी प्याज किस्म कौन सी है?", meta: "राजू, नाशिक · 12 जवाब" },
      { title: "टमाटर लीफ ब्लाइट को जल्दी कैसे रोकें?", meta: "सविता, पुणे · 8 जवाब" },
      { title: "आज गेहूं का सबसे अच्छा भाव किस मंडी में मिला?", meta: "गणेश, अमरावती · 5 जवाब" }
    ],
    aiReplies: {
      disease: "देखें कि धब्बे फैल रहे हैं, पीली सीमा वाले हैं या अधिक नमी से जुड़े हैं। प्रभावित पत्तियाँ हटाएँ, ऊपर से सिंचाई न करें, और गंभीरता के अनुसार फसल-विशिष्ट उपचार करें। बेहतर मार्गदर्शन के लिए आप इमेज भी अपलोड कर सकते हैं।",
      market: "गुणवत्ता सत्यापित होने पर सीधे खरीदार के दाम अक्सर बिचौलियों से बेहतर होते हैं। बेचने से पहले मंडी, सीधे खरीदार और व्यापारी दरों की तुलना करें। मैं यह भी बता सकता हूँ कि अभी बेचना है या इंतजार करना है।",
      weather: "मौसम स्प्रे समय, रोग जोखिम और फसल उपयुक्तता बदल देता है। अगर वर्षा कम रहती है तो बिना सिंचाई के सोयाबीन की बजाय दालें या बाजरा सुरक्षित हो सकते हैं।",
      schemes: "मैं PM-Kisan, PMFBY, सोइल कार्ड सहायता या सिंचाई सब्सिडी समझा सकता हूँ। बताइए कि आपको पात्रता, दस्तावेज़ या आवेदन चरण चाहिए।",
      app: "मैं ऐप चलाने में भी मदद कर सकता हूँ। मुझसे कहें जैसे crop care खोलो, prices दिखाओ, या dashboard समझाओ।"
    }
  },
  mr: {
    brandSub: "स्मार्ट शेती साथी",
    quickAccess: "त्वरित प्रवेश",
    moreFeatures: "वैशिष्ट्ये",
    homeDashboardTitle: "डॅशबोर्ड",
    homeDashboardDesc: "अलर्ट, माहिती आणि पुढील कृतींसह दैनंदिन आढावा",
    homeMarketTitle: "बाजार भाव",
    homeMarketDesc: "लाइव्ह बाजार आणि थेट खरेदीदार दर एकाच ठिकाणी पहा",
    homeCareTitle: "पीक काळजी",
    homeCareDesc: "रोग ओळख, प्रतिबंध, उपचार आणि इमेज मदत",
    homeAiTitle: "AI सहाय्यक",
    homeAiDesc: "हिंदी, मराठी किंवा इंग्रजीत त्वरित शेती सल्ला घ्या",
    homeWeatherTitle: "हवामान अंदाज",
    homeWeatherDesc: "बदलत्या परिस्थितीसाठी हवामान अपडेट्स आणि पीक सूचना",
    homeSchemesTitle: "शासकीय योजना",
    homeSchemesDesc: "PM-Kisan, विमा, सबसिडी आणि माती सहाय्य",
    homeCommunityTitle: "कम्युनिटी फोरम",
    homeCommunityDesc: "इतर शेतकऱ्यांकडून शिका आणि प्रश्न विचारा",
    homeAuthTitle: "लॉगिन / साइनअप",
    homeAuthDesc: "मोबाईल-अनुकूल फॉर्मसह शेतकरी आणि अॅडमिन प्रवेश",
    navHome: "मुख्य",
    navMarket: "बाजार",
    navAi: "AI",
    navProfile: "प्रोफाइल",
    homeGreeting: "नमस्कार, किसानजी",
    homeTagline: "तुमचा स्मार्ट\nशेती साथी",
    homeSub: "रिअल-टाइम बाजारभाव · हवामान मार्गदर्शन · पीक काळजी · AI मदत",
    weatherStrip: "अमरावती · 28°C · लाइव्ह शेती अपडेट्स उपलब्ध",
    loginHeader: "लॉगिन",
    signupHeader: "साइनअप",
    aiPlaceholder: "तुमचा संदेश येथे लिहा...",
    loginTitle: "किसान मार्गमध्ये लॉगिन करा",
    loginSub: "शेतकरी किंवा अॅडमिन म्हणून प्रवेश करा. हे खऱ्या मोबाईल अॅपसारखे डिझाइन केले आहे जे नंतर Android मध्ये wrap करता येईल.",
    loginEmail: "ईमेल किंवा फोन",
    loginPassword: "पासवर्ड",
    loginRole: "या रूपात लॉगिन करा",
    loginBtn: "लॉगिन",
    signupBtn: "साइनअप",
    signupTitle: "शेतकरी प्रोफाइल तयार करा",
    signupSub: "एकदाच नोंदणी करा आणि मोबाईल-फर्स्ट फ्लोमध्ये डॅशबोर्ड, AI मदत, बाजार अपडेट्स आणि पीक काळजी वापरा.",
    signupName: "पूर्ण नाव",
    signupPhone: "फोन",
    signupVillage: "गाव",
    signupDistrict: "जिल्हा",
    signupLanguage: "प्राधान्य भाषा",
    signupLand: "जमीन धारण",
    signupCrops: "मुख्य पिके",
    createAccount: "खाते तयार करा",
    back: "मागे",
    dashboardHeader: "डॅशबोर्ड",
    dashboardWelcome: "पुन्हा स्वागत,",
    todayFirst: "आज प्रथम",
    statWeather: "हवामान",
    statWeatherHelp: "सायं. 6 नंतर पावसाची शक्यता",
    statBestRate: "गव्हाचा सर्वोत्तम दर",
    statBestRateHelp: "व्यापारी ऑफरपेक्षा जास्त",
    support: "सहाय्य",
    dashMarketTitle: "बाजार",
    dashMarketDesc: "आजचा सर्वोत्तम विक्री दर पहा",
    dashCareTitle: "पीक काळजी",
    dashCareDesc: "रोग, प्रतिबंध, उपचार",
    dashAiTitle: "AI बॉट",
    dashAiDesc: "सोप्या भाषेत मदत",
    dashAdminTitle: "अॅडमिन",
    dashAdminDesc: "प्रोफाइल्स आणि स्टोरेज",
    dashWeatherTitle: "हवामान आणि जलवायू सूचना",
    dashWeatherDesc: "बदलत्या परिस्थितीनुसार पीक सूचना मिळवा",
    dashProfileTitle: "प्रोफाइल",
    dashProfileDesc: "शेतकरी ओळख, पिके आणि पसंती",
    marketHeader: "बाजारभाव",
    marketSub: "भारतीय कृषी बाजारांमधील लाइव्ह मंडी दर",
    selectCrop: "पीक निवडा",
    marketTableMarket: "बाजार",
    marketTableLocation: "स्थान",
    marketTableRate: "दर",
    marketMinPrice: "किमान",
    marketModalPrice: "मोडल",
    marketMaxPrice: "कमाल",
    marketDirectBuyer: "थेट खरेदीदार",
    marketMandi: "APMC मंडी",
    marketTrader: "मध्यस्थ ऑफर",
    bestPriceToday: "आजचा सर्वोत्तम दर",
    marketTrend: "दर कल",
    marketCompareTitle: "शीर्ष बाजार तुलना",
    marketLiveBadge: "लाइव्ह",
    marketLoading: "लाइव्ह बाजारभाव लोड होत आहेत...",
    marketNoData: "या निवडीसाठी लाइव्ह मंडी दर मिळाले नाहीत.",
    marketErrorLoad: "आत्ता लाइव्ह बाजारभाव लोड करता आले नाहीत.",
    marketFallbackNote: "लाइव्ह डेटा उपलब्ध होईपर्यंत नमुना दर दाखवले जात आहेत.",
    cropCareHeader: "पीक काळजी",
    cropDoctorTitle: "AI पीक डॉक्टर",
    cropDoctorDesc: "लक्षणे साध्या भाषेत सांगा किंवा रोग, प्रतिबंध आणि उपचार मार्गदर्शनासाठी इमेज इनपुट वापरा.",
    imagePlaceholder: "पान, फळ, खोड आणि कीड-हानी ओळखीसाठी इमेज अपलोड प्लेसहोल्डर",
    openAiDiagnosis: "AI निदान उघडा",
    askCommunity: "कम्युनिटीला विचारा",
    detectTitle: "लक्षणे",
    detectDesc: "पान वाकणे, पिवळे डाग, बुरशी, कोमेजणे, कीड छिद्रे, पोषण कमतरता",
    preventTitle: "प्रतिबंध",
    preventDesc: "अंतर, पाणी नियंत्रण, शेत स्वच्छता, चांगले बियाणे, योग्य फवारणी वेळ",
    treatTitle: "उपचार",
    treatDesc: "सुरक्षित उपचार सूचना, सेंद्रिय पर्याय, रासायनिक मदत आणि तज्ञ मार्गदर्शन",
    detectBadge: "ओळखा",
    preventBadge: "थांबवा",
    treatBadge: "उपचार",
    aiHeader: "AI सहाय्यक",
    aiTitle: "किसानबॉट",
    aiDesc: "अॅप वापर मदत, पीक आरोग्य सूचना, पीक रोग, प्रतिबंध, उपचार, हवामान अपडेट्स आणि पीक सूचना.",
    aiPromptGreeting: "नमस्कार",
    aiPromptCrop: "पीक सल्ला",
    aiPromptPest: "कीड नियंत्रण",
    aiPromptMarket: "बाजारभाव",
    aiPromptDisease: "पान रोग",
    aiPromptClimate: "जलवायू पिके",
    aiPromptApp: "अॅप मदत",
    aiWelcome: "नमस्कार! पिके, हवामान, रोग, बाजारभाव किंवा अॅप वापराबद्दल काहीही विचारा.",
    imageInputPlaceholder: "पीक आणि पान विश्लेषणासाठी इमेज इनपुट प्लेसहोल्डर",
    voiceInput: "आवाज इनपुट",
    voiceRecording: "ऐकत आहे...",
    voiceTranscribing: "प्रोसेस होत आहे...",
    voiceCropPrompt: "तुमची पीक समस्या बोला, मी ती AI निदानात नेईन.",
    voiceReady: "व्हॉइस नोट AI निदानासाठी तयार आहे",
    voiceError: "आवाज इनपुट आत्ता पूर्ण होऊ शकला नाही.",
    voiceUnsupported: "या डिव्हाइसवर व्हॉइस इनपुट Chrome मध्ये चांगले काम करते.",
    send: "पाठवा",
    weatherHeader: "हवामान आणि जलवायू",
    weatherSearchPlaceholder: "शहर शोधा (उदा. अमरावती, पुणे, नाशिक)",
    weatherSearchBtn: "शोधा",
    weatherClearBtn: "साफ करा",
    weatherQuickLabel: "त्वरित पर्याय",
    weatherRecentsLabel: "अलीकडील",
    weatherCurrentTitle: "आत्ता",
    weatherMetaTitle: "झटपट माहिती",
    weatherForecastTitle: "7-दिवसांचा अंदाज",
    weatherLocalTime: "स्थानिक वेळ",
    weatherFeelsLike: "जाणवते",
    weatherWind: "वारा",
    weatherPrecip: "पर्जन्य",
    weatherClouds: "ढग",
    weatherDayNight: "दिवस/रात्र",
    weatherTimezone: "टाइमझोन",
    weatherLatitude: "अक्षांश",
    weatherLongitude: "रेखांश",
    weatherElevation: "उंची",
    weatherDay: "दिवस",
    weatherNight: "रात्र",
    weatherLoading: "लाइव्ह हवामान लोड होत आहे...",
    weatherLoadingSearch: "ठिकाणे शोधली जात आहेत...",
    weatherErrorShort: "कृपया किमान 2 अक्षरे टाका.",
    weatherErrorNoMatch: "जुळणारे शहर सापडले नाही.",
    weatherErrorSearch: "शोध अयशस्वी झाला. कृपया पुन्हा प्रयत्न करा.",
    weatherErrorLoad: "आत्ता हवामान लोड करता आले नाही.",
    weatherResultSub: "लाइव्ह अंदाज आणि सद्य स्थिती",
    schemesHeader: "शासकीय योजना",
    communityHeader: "कम्युनिटी फोरम",
    profileHeader: "प्रोफाइल",
    profileDesc: "शेतकरी खाते, पिके आणि मोबाईल अॅप पसंती",
    adminTitle: "अॅडमिन स्टोरेज",
    adminDesc: "प्रोफाइल व्यवस्थापन नोंदी उघडा",
    adminHeader: "अॅडमिन स्टोरेज",
    adminManageTitle: "प्रोफाइल व्यवस्थापन",
    adminManageDesc: "अॅप फ्लोसाठी स्थानिक डेमो स्टोरेजमध्ये शेतकरी आणि अॅडमिन नोंदी",
    adminSearch: "प्रोफाइल शोधा",
    weatherBadge: "जलवायू",
    schemeBadge: "योजना",
    forumBadge: "फोरम",
    activeStatus: "सक्रिय",
    pendingStatus: "पडताळणी प्रलंबित",
    farmerId: "शेतकरी आयडी",
    villageDistrict: "गाव आणि जिल्हा",
    phoneLabel: "फोन",
    preferredLanguage: "प्राधान्य भाषा",
    landHolding: "जमीन धारण",
    currentCrops: "सध्याची पिके",
    weatherItems: [
      { title: "आज", note: "28°C · सौम्य वारा · पेरणीसाठी चांगले", crop: "सायंकाळपर्यंत आर्द्रता कमी झाल्यावरच कापूस फवारणी करा." },
      { title: "उद्या", note: "26°C · सायं. 6 नंतर पाऊस", crop: "पावसापूर्वी खत फवारणी टाळा." },
      { title: "जलवायू नोंद", note: "जवळच्या जिल्ह्यांत कमी पावसाचा कल", crop: "सिंचन नसल्यास सोयाबीनपेक्षा बाजरी आणि कडधान्ये सुरक्षित आहेत." }
    ],
    schemeItems: [
      { name: "PM-Kisan", desc: "पात्र शेतकऱ्यांसाठी थेट हप्त्यांमध्ये उत्पन्न सहाय्य." },
      { name: "PMFBY", desc: "पीक नुकसान आणि जलवायू हानीसाठी विमा सहाय्य." },
      { name: "मृदा आरोग्य पत्रिका", desc: "माती चाचणी आणि पोषकतत्व आधारित शेती सूचना." }
    ],
    communityItems: [
      { title: "या हंगामासाठी सर्वोत्तम कांदा जात कोणती?", meta: "राजू, नाशिक · 12 उत्तरे" },
      { title: "टोमॅटो लीफ ब्लाइट लवकर कसा थांबवू?", meta: "सविता, पुणे · 8 उत्तरे" },
      { title: "आज गव्हाला सर्वोत्तम दर कोणत्या मंडीत मिळाला?", meta: "गणेश, अमरावती · 5 उत्तरे" }
    ],
    aiReplies: {
      disease: "डाग पसरत आहेत का, पिवळ्या कडा आहेत का किंवा जास्त आर्द्रतेशी संबंधित आहेत का ते पहा. जास्त प्रभावित पाने काढा, वरून पाणी देणे टाळा आणि तीव्रतेनुसार पीक-विशिष्ट उपचार वापरा. अधिक चांगल्या मार्गदर्शनासाठी तुम्ही इमेज अपलोड करू शकता.",
      market: "गुणवत्ता पडताळली असल्यास थेट खरेदीदाराचे दर मध्यस्थांपेक्षा चांगले असतात. विक्रीपूर्वी मंडी, थेट आणि व्यापारी दर तुलना करा. लगेच विकायचे की थांबायचे हेही मी सांगू शकतो.",
      weather: "हवामान फवारणी वेळ, रोग धोका आणि पीक उपयुक्तता बदलते. पाऊस कमी राहिल्यास सिंचनाशिवाय सोयाबीनपेक्षा कडधान्ये किंवा बाजरी सुरक्षित ठरू शकतात.",
      schemes: "मी PM-Kisan, PMFBY, मृदा सहाय्य किंवा सिंचन सबसिडी समजावू शकतो. पात्रता, कागदपत्रे किंवा अर्ज टप्पे यापैकी काय हवे ते सांगा.",
      app: "मी अॅप वापरायलाही मदत करू शकतो. जसे crop care उघडा, prices दाखवा, किंवा dashboard समजवा असे विचारा."
    }
  }
};
